# Generated by Django 6.0.4 on 2026-05-07 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_leaves',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='used_leaves',
            field=models.IntegerField(default=0),
        ),
    ]
