# Generated by Django 6.0.4 on 2026-05-08 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='ProLeave Tech', max_length=255)),
                ('annual_leaves', models.IntegerField(default=20)),
                ('sick_leaves', models.IntegerField(default=12)),
                ('notifications', models.BooleanField(default=True)),
                ('allow_zero', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
